### PR TITLE
French translation, thanks to LaPalice

### PR DESCRIPTION
**Pull request by clochix**
Hi @frankrousseau,

@LaPalice would like to see how the french translation renders.
Could you merge this (WIP), publish to our pre-production server and send her the URL?
Thanks!

### CODE REVIEW

**Comment by frankrousseau** [comment]
OK

**Comment by LaPalice** [comment]
Can I have the link please ? Thanks !

**Comment by frankrousseau** [comment]
Sorry I forgot to give you the link: https://    staging.   cozy.io/fr/   Remove spaces. I added them because I don't want that site to be indexed by google.

**Comment by LaPalice** [comment]
Ok thanks

**Pull request merged**
